### ISSUE TITLE
Add left-nav (dark) 

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs3#3]
This should be a template for 2-column pages.

**Comment by oubiwann** [comment]
Full-height:
- http://stackoverflow.com/questions/19089384/twitter-bootstrap-3-two-columns-full-height
- http://jsfiddle.net/avrahamcool/vtxnF/10/ (using bootstrap classes)

**Comment by oubiwann** [comment]
Did a bunch of work on this last night only to find that having a separate `<nav>` block from the top nav results in smaller (phone) views completely missing the side-bar nav.

I'll redo this with an integrated approach like it used in the Bootstrap admin templates.

_sigh_

**Comment by rvirding** [comment]
I don't know where to put this as I can't find the original issue. It was an example Apache page (? iirc) with 3 columns of links, each with a picture. I personally don't like having pictures because they often don't provide any useful information so in the docs list I would prefer to just have titled links.

For an example of what I mean look at erlang solutions new home page.

Bttw where was this discussion?

**Comment by oubiwann** [comment]
Hrm, not sure what conversation you're talking about?

Here's the latest mock-up for the LFE docs landing page (the theme drop-down in the top-nav will be removed):
- http://docs3.lfe.io/examples/prototype-landing.html

That has large icons + text (not icons-only, which I also don't like ... I need text!)  But I do like having images + text, since that makes it visually more interesting. And I'm a visual person :-)

If you scroll below-the-fold on that mockup, a selection of documentation categories are provided. If users don't see this (e.g., if they are using phones or have older/smaller monitors), it's no big deal, since these categories will be displayed in a left-nav for all non-landing-page documentation pages. It's just added flavour for the landing page :-)

**Comment by oubiwann** [comment]
Ah! I think I know which one you mean, now:
- [Identify good examples of API documentation](https://github.com/lfe/docs/issues/37)

It has a link to AWS documentation, and they have an "icon carousel" above their docs categories ... with _no text whatsoever_ ... and, yeah, completely unusable to me. In fact, my eyes ignored it altogether and simply browsed the forest of docs links below ;-)

**Comment by oubiwann** [comment]
Just committed.
