### ISSUE TITLE
Support multiple themes for docs.lfe.io

### ISSUE THREAD

**Issue by oubiwann** [lfe/docs3#8]
Hell, we're using a theme derived from [Bootswatch](https://bootswatch.com/slate/) -- why not support all of them? Those who like dark can use the default; those who like light, can switch.

Tasks:
- [ ] Take a poll on the mail list (or a ticket) and find out which other Bootswatch themes people like the most 
- [ ] Add top 2 or 3 favourite themes to source
- [ ] Add cookie/session support
- [ ] Add theme drop-down to top nav
- [ ] Update other themes with new LFE sass variables

**Comment by rvirding** [comment]
I wonder. Wouldn't it be better to just have one theme for the whole site? _The LFE theme_

**Comment by oubiwann** [comment]
That would certainly be my preference :-) 

I like the darker look -- it's much, much easier on my eyes (I can't actually read white websites -- they are too bright for me).

As such, I wouldn't make this a very high-priority set of tasks -- more of a back-burner kind of thing. Once the site is up and we start getting requests for a lighter theme, we can move this to a front burner :-)

**Comment by rvirding** [comment]
I rather like the dark theme as well. Maybe a bit lighter but definitely no desire to make it very light. But we have to make sure that the LFE mug looks good against it. And of course my father's parentheses. :-)

**Comment by oubiwann** [comment]
Yeah, I'm with you on that.

Also, since we're doing a staticly-generated site, session tracking is more cumbersome. Not really in the mood to figure out a hack with cookies or to generate a full site for each theme :-/

I'm just going to take the theme menu out of the top-nav and use the one we've got (and that we like!).
